export const SUBJECT_META: Record<string, { icon: string; label: string }> = {
  math:        { icon: "🔢", label: "Math" },
  science:     { icon: "🔬", label: "Science" },
  history:     { icon: "📜", label: "History" },
  geography:   { icon: "🗺️", label: "Geography" },
  english:     { icon: "📝", label: "English" },
  technology:  { icon: "💻", label: "Technology" },
  environment: { icon: "🌱", label: "Environment" },
  gk:          { icon: "🌍", label: "General Knowledge" },
  civics:      { icon: "🏛️", label: "Civics" },
  health:      { icon: "❤️", label: "Health" },
  sports:      { icon: "🏆", label: "Sports" },
  reasoning:          { icon: "🧩", label: "Reasoning" },
  lifeskills:         { icon: "🎯", label: "Life Skills" },
  "creative-thinking": { icon: "💡", label: "Creative Thinking" },
  "study-skills":     { icon: "📚", label: "Study Skills" },
  hindi:              { icon: "🔤", label: "Hindi" },
  general:            { icon: "✨", label: "General" },
};
